-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS ClassroomBorrowingManagementSystem;
USE ClassroomBorrowingManagementSystem;

-- CREATE USER
CREATE USER IF NOT EXISTS 'sa'@'localhost' IDENTIFIED BY '123456'
GRANT ALL ON `ClassroomBorrowingManagementSystem`.* TO 'sa'@'localhost';
FLUSH PRIVILEGES;

-- CREATE TABLE
CREATE TABLE IF NOT EXISTS Classroom(
	ID VARCHAR(20) PRIMARY KEY COMMENT '教室ID',
	XiaoQu NVARCHAR(20) COMMENT '校区',
	JiaoXueQu NVARCHAR(20) COMMENT '教学区',
	JiaoXueLou NVARCHAR(20) NOT NULL COMMENT '教学楼',
	Capacity SMALLINT UNSIGNED COMMENT '容量'
) CHARSET=utf8 COMMENT '教室信息表';
CREATE TABLE IF NOT EXISTS User(
	ID VARCHAR(20) PRIMARY KEY COMMENT '用户ID',
	Name NVARCHAR(20) COMMENT '用户名',
	Password VARCHAR(30) COMMENT '密码',
	Level CHAR(10) COMMENT '用户等级',
	Phone CHAR(15) COMMENT '电话号码',
	Email CHAR(50) COMMENT '电子邮箱',
	Department NVARCHAR(30) COMMENT '部门'
) CHARSET=utf8 COMMENT '用户信息表';
CREATE TABLE IF NOT EXISTS ApplicationForm(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '教室申请表ID',
	UserID VARCHAR(20) COMMENT '申请者ID',
	RoomID VARCHAR(20) COMMENT '教室ID',
	SubmitTime DATETIME COMMENT '申请表提交时间',
	BeginUsingDate DATE COMMENT '申请起始使用时间',
	ZhouCi TINYINT COMMENT '周次',
	JieShu TINYINT COMMENT '节数',
	Purpose TEXT COMMENT '用途',
	Reviewer VARCHAR(20) COMMENT '审批人',
	ReviewTime DATETIME COMMENT '审批时间',
	Approval BOOLEAN COMMENT '审批意见'
) CHARSET=utf8 COMMENT '教室申请表';
CREATE TABLE IF NOT EXISTS RoomStatus(
	RoomID INT UNSIGNED COMMENT '教室ID',
	UserID VARCHAR(20) COMMENT '使用者ID',
	BeginUsingDate DATE COMMENT '使用起始日期',
	Purpose TEXT COMMENT '用途'
) CHARSET=utf8 COMMENT '教室状态表';